import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <nav className="bg-sidebar text-sidebar-foreground fixed top-0 left-0 w-full shadow-md px-6 py-4 border-b z-50 flex items-center ">

        {/* Logo na esquerda */}
        <div className="text-lg font-bold w-50 mr-6 h-10 ">
          <img src="/logoPartnerHorizontalCinza.png" alt="Logo versa Partner" className="w-full h-full object-contain" />
        </div>

        {/* Menu alinhado próximo à logo */}
        {/* <ul className="md:flex md:gap-6 md:ml-6 font-bold ">
          <li><a href="#" className="flex items-center gap-1">Trocar Dominio</a></li>
          {/* <li><a href="#" className="flex items-center gap-1"><NotebookPen size={24} />Vendas</a></li>
          <li><a href="#" className="flex items-center gap-1"><ClipboardList size={24} />Controladoria</a></li>
          <li><a href="#" className="flex items-center gap-1"><Warehouse size={24} />Estoque</a></li>
          <li><a href="#" className="flex items-center gap-1"><Wallet size={24} />Financeiro</a></li>
          <li><a href="#" className="flex items-center gap-1"><LampDesk size={24} />Editorial</a></li>
          <li><a href="#" className="flex items-center gap-1"><Paintbrush size={24} />Serviço</a></li>
          <li><a href="#" className="flex items-center gap-1"><LayoutGrid size={24} />Aplicativos</a></li> 
        </ul> */}

        {/* Ícones no canto direito */}
        <div className="flex items-center gap-3 ml-auto"> 
        <a href="#" className="flex items-center gap-1">Trocar Dominio</a>
        </div> 

      </nav>
      <body>
        {children}
      </body>
    </html>
  );
}
